### ISSUE TITLE
Raise AssertionError in adaptive_parzen_normal

### ISSUE THREAD

**Issue by garnieje** [hyperopt/hyperopt#227]
Hello,

When running hyperopt (the function optimize) I raised the following exception:

```
Traceback (most recent call last):
  File "hyperoptnn.py", line 151, in <module>
    optimize(trials)
  File "hyperoptnn.py", line 130, in optimize
    best = fmin(score, space, algo=tpe.suggest, trials=trials, max_evals = 300)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 334, in fmin
    rval.exhaust()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 294, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 249, in run
    new_trials = algo(new_ids, self.domain, trials)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/tpe.py", line 902, in suggest
    print_node_on_error=False)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/pyll/base.py", line 860, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/tpe.py", line 464, in adaptive_parzen_normal
    assert prior_sigma > 0
AssertionError
```

Any clues where that might be coming from? Is it because of the range of one of my parameters is not valid? Any ideas fi it?

Thanks in advance,  
Jérôme.

**Comment by jaberg** [comment]
This has come up recently on the google groups mailing list I think, did
you find a posting like that?  There's probably a better error message to
print, but I think the person ended up fixing something about his
application code.

**Comment by pkainz** [comment]
Check if the `low` and `high` arguments are correctly set in your definition of the parameter distribution.
In #221 the situation is similar: 
```python
# original space definition
hp.loguniform("L2", np.log(10**(-2)), np.log(10**(-7)))

# internal computation
low = np.log(10**(-2))   # = -4.605 
high = np.log(10**(-7))  # = -16.11
```
results in
```python
prior_sigma = 1.0 * (-16.11 + 4.605)   # = -11.505
```
and causes the `AssertionError`.

If you swap `low` and `high`, everything should be good:
```python
hp.loguniform("L2",np.log(10**(-7)), np.log(10**(-2)))
# ...
prior_sigma = 1.0 * (-4.605 + 16.11)   # = 11.505
```

**Comment by trevorwelch** [comment]
I tried a bunch of different values in my param space trying to get `hp.quniform` to avoid this error but wasn't successful. Ultimately switching to `hp.choice` seems to have fixed it. I imagine I had something wrong in the way I was using `hp.quniform` but I wasn't able to figure out what!

**Comment by neuronalX** [comment]
@trevorwelch I had the same issue with hp.quniform when I tried to fix a given value (i.e. keep it constant without removing some parameters from the search_space) and I found in which cases it works:
     hp.quniform('N', 20, 21, 20),
--> this works
     hp.quniform('N', 20, 20, 20),
--> this doesn't

Both would give you a constant value of N=20, but the assert "don't let" you have low==high for hp.quniform(label, low, high, q).

The same happens for hp.uniform():
    hp.uniform('iss',10., 10.)
--> this doesn't work either because low==high.

@jaberg Is there a reason to keep the assert this way?
    assert prior_sigma > 0
instead of this?
    assert prior_sigma >= 0
Does TPE require low!=high?

The tricky thing with this error, is that it is difficult to understand why it happens. You do not have such an error when using random search instead of TPE:
    algo=rand.suggest
And when using TPE, the error only appears after 20 iterations, or the number of random jobs when setting this option (here 100):
    algo=partial(tpe.suggest, n_startup_jobs=100)
So you could think there is a problem in your own algorithm, because it reaches 20 iterations ...
Raising an exception with a more explicit message would save some time understanding the issue.

**Comment by jmgo** [comment]
Thank you @neuronalX, I was having the same problem, but changing the hp.uniform to hp.choice when I only want 1 possibility for a parameter has solved my problem.

**Comment by neuronalX** [comment]
You are welcome @jmgo! Happy that it was useful!

**Comment by silverlining21** [comment]
> @trevorwelch I had the same issue with hp.quniform when I tried to fix a given value (i.e. keep it constant without removing some parameters from the search_space) and I found in which cases it works:
> `hp.quniform('N', 20, 21, 20),` --> this works
> `hp.quniform('N', 20, 20, 20),`--> this doesn't
> 
> Both would give you a constant value of N=20, but the assert "don't let" you have low==high for hp.quniform(label, low, high, q).
> 
> The same happens for hp.uniform():
> `hp.uniform('iss',10., 10.)` --> this doesn't work either because low==high.
> 
> @jaberg Is there a reason to keep the assert this way:
> `assert prior_sigma > 0` instead of `assert prior_sigma >= 0`?
> Does TPE require low!=high?
> 
> The tricky thing with this error, is that it is difficult to understand why it happens. You do not have such an error when using random search instead of TPE:
> `algo=rand.suggest`
> And when using TPE, the error only appears after 20 iterations, or the number of random jobs when setting this option (here 100):
> `algo=partial(tpe.suggest, n_startup_jobs=100)`
> So you could think there is a problem in your own algorithm, because it reaches 20 iterations ...
> Raising an exception with a more explicit message would save some time understanding the issue.

I stuck in the same bug, 20 times of iterations the exception was raised. Really, confused.

**Comment by silverlining21** [comment]
following my log

> [05/30/2019, 12:53:51 PM] INFO (hyperopt.tpe/Thread-1) TPE using 20/20 trials with best loss -0.989784
[05/30/2019, 12:53:51 PM] ERROR (nni.msg_dispatcher_base/Thread-1) 
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 102, in command_queue_worker
    self.process_command(command, data)
  File "/root/anaconda3/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 160, in process_command
    command_handlers[command](data)
  File "/root/anaconda3/lib/python3.7/site-packages/nni/msg_dispatcher.py", line 101, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids)
  File "/root/anaconda3/lib/python3.7/site-packages/nni/tuner.py", line 52, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id)
  File "/root/anaconda3/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 256, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/root/anaconda3/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 375, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/root/anaconda3/lib/python3.7/site-packages/hyperopt/tpe.py", line 900, in suggest
    print_node_on_error=False)
  File "/root/anaconda3/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/hyperopt/tpe.py", line 465, in adaptive_parzen_normal
    assert prior_sigma > 0

**Comment by silverlining21** [comment]
To supply, I have replace the `uniform` into `choice` of all possible params, I still go the same error

**Comment by Levinin** [comment]
I have just been battling with this same error. The problem went away when I changed my hyperas (hyperopt wrapper) model code from this:
model.add(tf.keras.layers.Dropout(  {{uniform(0, 0.3)}}  ))

To this:
model.add(tf.keras.layers.Dropout(  {{uniform(0.1e-12, 0.3)}}  ))

It seems that hyperopt doesn't like having a value of 0 as the low value. Just having the very small value instead has solved it for me.

**Comment by iirekm** [comment]
It also happens from time to time with `hp.uniformint(label, from, to)`, which is perfectly normal  if `from` == `to` under some circumstances. 

`hp.uniformint` should check for such corner conditions. The current workaround is `hp.uniformint(label) if from != to else from`.
