### ISSUE TITLE
Error with hyperas

### ISSUE THREAD

**Issue by MrWanter** [hyperopt/hyperopt#257]
I have establised theano and keras enviorment and have run example code successfully, but after I installed hyperas by 'pip install hyperas' and run the example code of hyperas, it raise an error and I don't know how to fix it, anyone can help me, thanks in advances! below is the error information:

`Unexpected error: <type 'exceptions.NameError'>
Traceback (most recent call last):

  File "<ipython-input-2-570b570a6029>", line 1, in <module>
    runfile('C:/SciSoft/my_code/test_hyperas.py', wdir='C:/SciSoft/my_code')

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/SciSoft/my_code/test_hyperas.py", line 211, in <module>
    trials=Trials())

  File "c:\scisoft\winpython-64bit-2.7.9.4\python-2.7.9.amd64\hyperas-\hyperas\optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)

  File "c:\scisoft\winpython-64bit-2.7.9.4\python-2.7.9.amd64\hyperas-\hyperas\optim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space

  File "temp_model.py", line 8, in <module>
    spy_cfg.IPKernelApp.pylab_import_all = autoload_pylab_o

NameError: name 'autoload_pylab_o' is not defined`

**Comment by MrWanter** [comment]
`豆腐干`

**Comment by MrWanter** [comment]
`Unexpected error: <type 'exceptions.NameError'>
Traceback (most recent call last):

  File "<ipython-input-2-570b570a6029>", line 1, in <module>
    runfile('C:/SciSoft/my_code/test_hyperas.py', wdir='C:/SciSoft/my_code')

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/SciSoft/my_code/test_hyperas.py", line 211, in <module>
    trials=Trials())

  File "c:\scisoft\winpython-64bit-2.7.9.4\python-2.7.9.amd64\hyperas-\hyperas\optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)

  File "c:\scisoft\winpython-64bit-2.7.9.4\python-2.7.9.amd64\hyperas-\hyperas\optim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space

  File "temp_model.py", line 8, in <module>
    spy_cfg.IPKernelApp.pylab_import_all = autoload_pylab_o

NameError: name 'autoload_pylab_o' is not defined`

**Comment by maxpumperla** [comment]
@MrWanter this is a problem using hyperas with ipython, so it's not hyperopt related. Going to close this (feel free to report as issue in hyperas, again, though)
