### ISSUE TITLE
Hyperopt installation on Windows using Anaconda

### ISSUE THREAD

**Issue by shahlaebrahimi** [hyperopt/hyperopt#280]
I would greatly appreciate if you could let me know how to install Hyperopt  using anaconda on windows 10. I tried this instruction to install it as it shows below:

```
(C:\Users\Markazi.co\ Anaconda3) C:\Users\Markazi.co>conda install -c jaikumarm hyperopt=0.1
Fetching package metadata ...........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current win-64 channels:
  - hyperopt 0.1*
You can search for packages on anaconda.org with
    anaconda search -t conda hyperopt
(C:\Users\Markazi.co\ Anaconda3) C:\Users\Markazi.co>conda install -c jaikumarm hyperopt
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Users\Markazi.co\Anaconda3:
#
hyperopt                  0.0.3.dev                py35_0    jaikumarm
(C:\Users\Markazi.co\ Anaconda3) C:\Users\Markazi.co>

```
Although it seems that the packages are installed, this error is reported:
```
from hyperopt import hp, fmin, tpe
ImportError: cannot import name 'hp'

```
Then, I tried to install it using python:

```
(C:\Users\Markazi.co\Anaconda3) C:\Users\Markazi.co>conda remove -c jaikumarm hyperopt
Fetching package metadata ...........
Solving package specifications: ..........
Package plan for package removal in environment C:\Users\Markazi.co\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-9.0.1                  |           py35_1         1.7 MB

The following packages will be REMOVED:
    hyperopt: 0.0.3.dev-py35_0 jaikumarm
The following packages will be UPDATED:
    pip:      8.1.2-py35_0               --> 9.0.1-py35_1
Proceed ([y]/n)? y
Fetching packages ...
pip-9.0.1-py35 100% |###############################| Time: 0:00:01   1.05 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
(C:\Users\Markazi.co\Anaconda3) C:\Users\Markazi.co>conda update pip
Fetching package metadata .........
Solving package specifications: ..........
# All requested packages already installed.
# packages in environment at C:\Users\Markazi.co\Anaconda3:
#
pip                       9.0.1                    py35_1
(C:\Users\Markazi.co\Anaconda3) C:\Users\Markazi.co>pip install hyperopt
Collecting hyperopt
  Downloading hyperopt-0.1.tar.gz (98kB)
    100% |################################| 102kB 172kB/s
Requirement already satisfied: numpy in c:\users\markazi.co\anaconda3\lib\site-packages (from hyperopt)
Requirement already satisfied: scipy in c:\users\markazi.co\anaconda3\lib\site-packages (from hyperopt)
Requirement already satisfied: nose in c:\users\markazi.co\anaconda3\lib\site-packages (from hyperopt)
Requirement already satisfied: pymongo in c:\users\markazi.co\anaconda3\lib\site-packages (from hyperopt)
Requirement already satisfied: six in c:\users\markazi.co\anaconda3\lib\site-packages (from hyperopt)
Requirement already satisfied: networkx in c:\users\markazi.co\anaconda3\lib\site-packages (from hyperopt)
Collecting future (from hyperopt)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |################################| 829kB 107kB/s
Requirement already satisfied: decorator>=3.4.0 in c:\users\markazi.co\anaconda3\lib\site-packages (from networkx->hyperopt)
Building wheels for collected packages: hyperopt, future
  Running setup.py bdist_wheel for hyperopt ... done
  Stored in directory: C:\Users\Markazi.co\AppData\Local\pip\Cache\wheels\4b\0f\9d\1166e48523d3bf7478800f250b0fceae31ac6a08b8a7cca820
  Running setup.py bdist_wheel for future ... done
  Stored in directory: C:\Users\Markazi.co\AppData\Local\pip\Cache\wheels\c2\50\7c\0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built hyperopt future
Installing collected packages: future, hyperopt
Successfully installed future-0.16.0 hyperopt-0.1
(C:\Users\Markazi.co\Anaconda3) C:\Users\Markazi.co>

```
Again, it is installed but the same error is reported:

```
from hyperopt import hyperopt, fmin, tpe
ImportError: cannot import name 'hyperopt'
```

Best regards,

**Comment by jaikumarm** [comment]
didn't know anyone else was using the conda repo. can you try the latest one I uploaded today.

I tested it and it works correctly on my windows 10 desktop.
```
C:\Users\Jayakumar>conda install -c jaikumarm hyperopt=0.1
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Jayakumar\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    future-0.16.0              |           py35_0         618 KB
    pymongo-3.3.0              |           py35_0         305 KB
    requests-2.12.4            |           py35_0         791 KB
    hyperopt-0.1               |                0         171 KB  jaikumarm
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.2.15               |           py35_0         460 KB
    ------------------------------------------------------------
                                           Total:         2.4 MB

The following NEW packages will be INSTALLED:

    future:    0.16.0-py35_0
    hyperopt:  0.1-0         jaikumarm
    pymongo:   3.3.0-py35_0

The following packages will be UPDATED:

    conda:     4.2.9-py35_0            --> 4.2.15-py35_0
    pyopenssl: 16.0.0-py35_0           --> 16.2.0-py35_0
    requests:  2.11.1-py35_0           --> 2.12.4-py35_0

Proceed ([y]/n)? y

Fetching packages ...
future-0.16.0- 100% |###############################| Time: 0:00:00   6.07 MB/s
pymongo-3.3.0- 100% |###############################| Time: 0:00:00   4.68 MB/s
requests-2.12. 100% |###############################| Time: 0:00:00  11.89 MB/s
hyperopt-0.1-0 100% |###############################| Time: 0:00:00 286.54 kB/s
pyopenssl-16.2 100% |###############################| Time: 0:00:00   2.99 MB/s
conda-4.2.15-p 100% |###############################| Time: 0:00:00   5.99 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%


C:\Users\Jayakumar>python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyperopt
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>>

```

**Comment by shahlaebrahimi** [comment]
@jaikumarm Thanks a lot for your time and consideration. Unfortunately, it seems that there is a problem with it:


```
(C:\Users\Markazi.co\Anaconda3) C:\Users\Markazi.co>conda install -c jaikumarm hyperopt=0.1
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\Markazi.co\Anaconda3:
#
hyperopt                  0.1                           0    jaikumarm

(C:\Users\Markazi.co\Anaconda3) C:\Users\Markazi.co>
```

C:\Users\Markazi.co\Anaconda3\python.exe D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/hyperopt.py
Traceback (most recent call last):
```
  File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/hyperopt.py", line 5, in <module>
    from hyperopt import hp, fmin, tpe
  File "D:\mifs-master_2\MU\learning-from-imbalanced-classes-master\learning-from-imbalanced-classes-master\continuous\hyperopt.py", line 5, in <module>
    from hyperopt import hp, fmin, tpe
ImportError: cannot import name 'hp'

Process finished with exit code 1
```
Best regards,

**Comment by jaikumarm** [comment]
looks like you named the file hyperopt.py which is the same as the name of the module. the python interpreter is tying to import those functions from self.  try naming the file to hyperopt_example.py or something else and try. 

this is a good read on this issue
http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

**Comment by shahlaebrahimi** [comment]
@jaikumarm Hi.
Thaks a lot.
I would appreciate if you could let me know how to resolve this [issue](https://github.com/dmlc/xgboost/issues/1034)?
Best regards,

**Comment by rtygbwwwerr** [comment]
you can check your project whether includes a file named "hyperopt.py" or "hyperopt.pyc", if you found, delete them. I have encountered the same problem like you, and fixed it through this way.

**Comment by michaelmior** [comment]
Closing but feel free to reopen if you're still having an issue with a recent Hyperopt version.
