### ISSUE TITLE
How to use main_plot_vars()

### ISSUE THREAD

**Issue by cbaziotis** [hyperopt/hyperopt#281]
I have save the Trials object and now i want to inspect the results. So i tried the visualizations provided in [plotting.py](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/plotting.py). `main_plot_history` and `main_plot_histogram` word just fine by only passing the trials object, but `main_plot_vars` gives the following error:
```
Traceback (most recent call last):
  File ".../hp_model_selection.py", line 41, in <module>
    main_plot_vars(trials=trials, bandit=space)
  File "...\site-packages\hyperopt\plotting.py", line 152, in main_plot_vars
    for label in all_labels]
  File "...\site-packages\hyperopt\plotting.py", line 152, in <listcomp>
    for label in all_labels]
AttributeError: 'dict' object has no attribute 'params'
```
and following the code i see that it needs the `bandit` parameter, even though in the function definition it lists bandit as an optional parameter.
What is the bandit object and how can i use the  `main_plot_vars` funciton?

Thanks.

**Comment by Razlaw** [comment]
The usage changed at some point. 
By now you have to generate your own bandit to feed it to the main_plot_vars() function. 

Here is a small example:
`from hyperopt.plotting import main_plot_vars`
`from hyperopt import base`

`# setting up your search_space, objective_function, and trials goes here`
`# see the tutorials to know how `

`domain = base.Domain(objective_function, search_space)  `
`main_plot_vars(trials, bandit=domain)`

**Comment by Iamshg** [comment]
@Razlaw thanks
