### ISSUE TITLE
best_trial raises ValueError when no STATUS_OK trial is present

### ISSUE THREAD

**Issue by tyrion** [hyperopt/hyperopt#339]
Accessing `trials.best_trial` raises the following exception if the `trials` object contains no successful trial (i.e. `STATUS_OK`):
```
Traceback (most recent call last):
  File "/home/tyrion/.local/lib/virtualenvwrapper/trl/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1030, in argmin
    argmin = a.argmin
AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/tyrio/src/trl/trl/cli/commands.py", line 188, in run_hyperopt
    best = trials.best_trial
  File "/home/tyrion/.local/lib/virtualenvwrapper/trl/lib/python3.5/site-packages/hyperopt/base.py", line 585, in best_trial
    best = np.argmin(losses)
  File "/home/tyrion/.local/lib/virtualenvwrapper/trl/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1032, in argmin
    return _wrapit(a, 'argmin', axis, out)
  File "/home/tyrion/.local/lib/virtualenvwrapper/trl/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```
This is because the code is calling np.argmin on an empty list:
```python
@property
def best_trial(self):
    """Trial with lowest loss and status=STATUS_OK
    """
    candidates = [t for t in self.trials
                  if t['result']['status'] == STATUS_OK]
    losses = [float(t['result']['loss']) for t in candidates]
    assert not np.any(np.isnan(losses))
    best = np.argmin(losses)
    return candidates[best]
```

I don't think it's appropriate to return an exception from a property getter. I would suggest either returning `None` or changing `best_trial` to a method.

**Comment by YohanBT** [comment]
I also encountered same issue when there are no STATUS_OK trials.

Need to prevent exception coming from `assert not np.any(np.isnan(losses))`  when `losses ` is an empty list.

**Comment by sahertariq07** [comment]
Hello everyone!
I'm having same problem regarding 'nan' loss exception in hyperopt. Any solution how to avoid it??

**Comment by errodriguez** [comment]
Hi everyone! 

I'm facing something quite similar (same error message, actually), but in my case when the STATUS_FAIL must be issued. As far as I read in the documentation, returning `return {'status': STATUS_FAIL }` must be enough for Hyperopt, but I'm getting the same error as depicted  at the beggining of this issue. Is this a bug or I'm missing something?

**Comment by tpvasconcelos** [comment]
Is anyone working on this?

**Comment by tpvasconcelos** [comment]
Also, am I misreading [fmin](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py#L267)'s docstring or does [return_argmin](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py#L340)
```
return_argmin : bool, default True
    If set to False, this function returns nothing, which can be useful
    for example if it is expected that `len(trials)` may be zero after
    fmin, and therefore `trials.argmin` would be undefined.
```
contradict [Returns](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py#L365)
```
argmin : dictionary
    If return_argmin is True returns `trials.argmin` which is a dictionary.  Otherwise
    this function  returns the result of `hyperopt.space_eval(space, trails.argmin)` if there
    were succesfull trails. This object shares the same structure as the space passed.
    If there were no succesfull trails, it returns None.
```

**Comment by errodriguez** [comment]
In my case I opted to apply what someone suggest [in issue #522](https://github.com/hyperopt/hyperopt/issues/522). It works for me for the moment. I'm still evaluating other alternatives.

**Comment by pengcao** [comment]
I have the same problems,how to deal with it? thanks!
