### ISSUE TITLE
Hyperopt Import Error

### ISSUE THREAD

**Issue by rmanuuu** [hyperopt/hyperopt#342]
After installing hyperopt using pip, I get the following error on import:

```
$ python
Python 2.7.14 (default, Sep 25 2017, 09:53:22)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hyperopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/hyperopt/__init__.py", line 3, in <module>
    from .base import STATUS_STRINGS
  File "/usr/local/lib/python2.7/site-packages/hyperopt/base.py", line 44, in <module>
    from . import pyll
  File "/usr/local/lib/python2.7/site-packages/hyperopt/pyll/__init__.py", line 2, in <module>
    from .base import Apply
  File "/usr/local/lib/python2.7/site-packages/hyperopt/pyll/base.py", line 25, in <module>
    standard_library.install_aliases()
  File "/usr/local/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "test.py", line 6, in <module>
    c = np.hstack((a,b))
  File "/usr/local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 293, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input arrays must have same number of dimensions
```

Python Version: 2.7.14
Hyperopt Version: 0.1
OS: macOS Sierra

**Comment by michaelmior** [comment]
I'm going to close this since this refers to a very old version of hyperopt. If you're still having this problem, feel free to reopen.
