### ISSUE TITLE
Simple case does not work

### ISSUE THREAD

**Issue by thiagotei** [hyperopt/hyperopt#377]
Following the instructions for the simplest case I've got the following error:
```
Traceback (most recent call last):
  File "simplestcase.py", line 11, in <module>
    max_evals=100)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object has no attribute '__getitem__'
```

By simplest case I mean:
```python
from hyperopt import fmin, tpe, hp
best = fmin(fn=lambda x: x ** 2,
            space=hp.uniform('x', -10, 10),
                algo=tpe.suggest,
                    max_evals=100)
print bes
```

Any help is appreciated.
Thanks

**Comment by maxpumperla** [comment]
install hyperopt from master, release will come out soon.

**Comment by thiagotei** [comment]
Could you point you more details on that?

Thanks

**Comment by maxpumperla** [comment]
pip install git+https://github.com/hyperopt/hyperopt.git

**Comment by thiagotei** [comment]
Thanks
