### ISSUE TITLE
IMPORTANT! async = False syntax error in base.py Python 3.7

### ISSUE THREAD

**Issue by StylishTriangles** [hyperopt/hyperopt#407]
async is a new reserved keyword in Python 3.7
https://docs.python.org/3/whatsnew/3.7.html

```Python
import hyperopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chad/.local/share/virtualenvs/veles37-XWNqV4Wn/lib/python3.7/site-packages/hyperopt/__init__.py", line 3, in <module>
    from .base import STATUS_STRINGS
  File "/home/chad/.local/share/virtualenvs/veles37-XWNqV4Wn/lib/python3.7/site-packages/hyperopt/base.py", line 266
    async = False
          ^
SyntaxError: invalid syntax
```

#bug

**Comment by StylishTriangles** [comment]
#409
