### ISSUE TITLE
async compatibility in python3.7 

### ISSUE THREAD

**Issue by fayeshine** [hyperopt/hyperopt#430]
```
Traceback (most recent call last):

  File "/home/wenjian/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-e1ba1efe58cd>", line 1, in <module>
    import hyperopt

  File "/home/wenjian/anaconda3/lib/python3.7/site-packages/hyperopt-0.1-py3.7.egg/hyperopt/__init__.py", line 3, in <module>
    from .base import STATUS_STRINGS

  File "/home/wenjian/anaconda3/lib/python3.7/site-packages/hyperopt-0.1-py3.7.egg/hyperopt/base.py", line 266
    async = False
          ^
SyntaxError: invalid syntax
```

**Comment by bjkomer** [comment]
This has been fixed in the newest version, you can either upgrade with pip or install from master to get it
