### ISSUE TITLE
Travis with python 2.7 seems to be broken

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#456]
Travis with python 2.7 seems to be broken. See here:
https://travis-ci.org/hyperopt/hyperopt/jobs/478534726

Output is:
```
$ python -m pytest
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/python/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pytest.py", line 73, in <module>
    raise SystemExit(pytest.main())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 942, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 1107, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/_pytest/config.py", line 1070, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pluggy/__init__.py", line 402, in load_setuptools_entrypoints
    "Plugin %r could not be loaded: %s!" % (ep.name, e))
pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 3.3.0 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('pytest>=3.6'))!
The command "python -m pytest" exited with 1.
```

**Comment by maxpumperla** [comment]
@PhilipMay can you require pytest>=3.6 in your open PR to see if that fixes the problem (it should)

**Comment by PhilipMay** [comment]
> @PhilipMay can you require pytest>=3.6 in your open PR to see if that fixes the problem (it should)

I did it in `.travis.yml`. Hope that was right.

**Comment by PhilipMay** [comment]
Still with error: https://travis-ci.org/hyperopt/hyperopt/jobs/479570122

**Comment by maxpumperla** [comment]
yeah, that's a little unfortunate. I've triggered an old build that was previously green and it now has the same error. I suspect travis changed its runtime slightly, but I can't say for sure. Maybe for your PR let's revert it back and fix it separately / at a later point.

**Comment by jkbradley** [comment]
@WeichenXu123 found that using nosetests can fix this: https://github.com/hyperopt/hyperopt/pull/480
