### ISSUE TITLE
hyperopt.tests.test_rdists test fails. (We need make it deterministic)

### ISSUE THREAD

**Issue by WeichenXu123** [hyperopt/hyperopt#481]
The test in `hyperopt.tests.test_rdists` is nondeterministic.

Some of the failure test looks like:
**FAIL: test_bigq (hyperopt.tests.test_rdists.TestQNormal)**

Traceback (most recent call last):
  File "/home/travis/build/databricks/databricks-hyperopt/hyperopt/tests/test_rdists.py", line 230, in test_bigq
    check_d_samples(qn, n=10000)
  File "/home/travis/build/databricks/databricks-hyperopt/hyperopt/tests/test_rdists.py", line 124, in check_d_samples
    n, dfn.pmf(ii), p))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 93, in assert_
    raise AssertionError(smsg)
AssertionError: n = 10000; pmf = 0.138706; p = 0.126300
-------------------- >> begin captured stdout << ---------------------
('Error in sampling frequencies', -15)
value	pmf	freq
-36.00	0.000	0.0004
-33.00	0.002	0.0022
-30.00	0.015	0.0147
-27.00	0.068	0.0724
-24.00	0.181	0.1907
-21.00	0.284	0.2843
-18.00	0.259	0.2563
-15.00	0.139	0.1263
-12.00	0.043	0.0438
-9.00	0.008	0.0083
-6.00	0.001	0.0006
--------------------- >> end captured stdout << ----------------------

**FAIL: test_2points (hyperopt.tests.test_rdists.TestQLogUniform)**

Traceback (most recent call last):
  File "/home/travis/build/databricks/databricks-hyperopt/hyperopt/tests/test_rdists.py", line 191, in test_2points
    check_d_samples(qlu, n=10000)
  File "/home/travis/build/databricks/databricks-hyperopt/hyperopt/tests/test_rdists.py", line 124, in check_d_samples
    n, dfn.pmf(ii), p))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/numpy/testing/utils.py", line 75, in assert_
    raise AssertionError(smsg)
AssertionError: n = 10000; pmf = 0.594316; p = 0.577900
-------------------- >> begin captured stdout << ---------------------
('Error in sampling frequencies', 0.0)
value	pmf	freq
0.00	0.594	0.5779
0.50	0.406	0.4221

**Comment by maxpumperla** [comment]
@WeichenXu123 what do you propose to fix this?
