### ISSUE TITLE
Error Running Parallel with MongoDB

### ISSUE THREAD

**Issue by JadBatmobile** [hyperopt/hyperopt#514]
The following traceback is received on the worker end:

`Traceback (most recent call last):
  File "/usr/local/bin/hyperopt-mongo-worker", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1267, in main
    sys.exit(main_worker())
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1317, in main_worker
    return main_worker_helper(options, args)
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1261, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1085, in run_one
    result = worker_fn(spec, ctrl)
  File "/usr/local/lib/python3.6/site-packages/hyperopt/base.py", line 843, in evaluate
    print_node_on_error=self.rec_eval_print_node_on_error)
  File "/usr/local/lib/python3.6/site-packages/hyperopt/pyll/base.py", line 874, in rec_eval
    rval_var = node.pos_args[int(switch_i) + 1]
IndexError: list index out of range
`

Anyone know what this is?

**Comment by tawe141** [comment]
No idea, but I'm currently getting the same error without Mongo

**Comment by tawe141** [comment]
Are you by any chance defining initial points to evaluate? I found that turning this off made it run.
