### ISSUE TITLE
Installation via pip fails : " SSL is required "

### ISSUE THREAD

**Issue by AlbinoGeek** [hyperopt/hyperopt#567]
Following through the source install on Fedora 30 Workstation using Python 3.7.5 pip 19.0.3

```
$ python setup.py develop && pip install -e '.[MongoTrials, SparkTrials, ATPE]'
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.38.tar.gz     
Traceback (most recent call last):                                                                                                                                    File "setup.py", line 37, in <module>                                                                                                                                      
    distribute_setup.use_setuptools()                                                                                                                                        
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 152, in use_setuptools                                                                                        
    return _do_download(version, download_base, to_dir, download_delay)                                                                                                      
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 131, in _do_download                                                                                          
    to_dir, download_delay)                                                                                                                                                  
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 201, in download_setuptools                                                                                   
    src = urlopen(url)                                                                                                                                                       
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen                                                                                                               
    return opener.open(url, data, timeout)                                                                                                                                   
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open                                                                                                                  
    response = meth(req, response)                                                                                                                                           
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response                                                                                                         
    'http', request, response, code, msg, hdrs)                                                                                                                              
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error                                                                                                                 
    return self._call_chain(*args)                                                                                                                                           
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain                                                                                                           
    result = func(*args)                                                                                                                                                     
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default                                                                                                    
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)                                                                                                                 
urllib2.HTTPError: HTTP Error 403: SSL is required  
```

**Comment by AlbinoGeek** [comment]
Fixing the missing `https` in the `DOWNLOAD_URL` still presents the following errors

## when using Python 2

```
Extracting in /tmp/tmpeI5_y_                                                                                                                                                 
Now working in /tmp/tmpeI5_y_/distribute-0.6.38                                                                                                                              
Building a Distribute egg in /home/damon/go/src/hyperopt                                                                                                                     
Traceback (most recent call last):                                                                                                                                           
  File "setup.py", line 248, in <module>                                                                                                                                     
    scripts = scripts,                                                                                                                                                       
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup                                                                                                          
    _setup_distribution = dist = klass(attrs)                                                                                                                                
  File "/tmp/tmpeI5_y_/distribute-0.6.38/setuptools/dist.py", line 225, in __init__                                                                                          
    _Distribution.__init__(self,attrs)                                                                                                                                       
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__                                                                                                       
    self.finalize_options()
  File "/tmp/tmpeI5_y_/distribute-0.6.38/setuptools/dist.py", line 257, in finalize_options                                                                                  
    ep.require(installer=self.fetch_build_egg)                                                                                                                               
  File "/tmp/tmpeI5_y_/distribute-0.6.38/pkg_resources.py", line 2027, in require                                                                                            
    working_set.resolve(self.dist.requires(self.extras),env,installer))                                                                                                      
  File "/tmp/tmpeI5_y_/distribute-0.6.38/pkg_resources.py", line 2237, in requires
    dm = self._dep_map
  File "/tmp/tmpeI5_y_/distribute-0.6.38/pkg_resources.py", line 2466, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmpeI5_y_/distribute-0.6.38/pkg_resources.py", line 2499, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmpeI5_y_/distribute-0.6.38/pkg_resources.py", line 2496, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmpeI5_y_/distribute-0.6.38/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    distribute_setup.use_setuptools()
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 123, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.```

## when using Python 3
```
Extracting in /tmp/tmpsatzu29l
Traceback (most recent call last):
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 150, in use_setuptools
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    distribute_setup.use_setuptools()
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 152, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 132, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 105, in _build_egg
    _extractall(tar)
  File "/home/damon/go/src/hyperopt/distribute_setup.py", line 500, in _extractall
    self.chown(tarinfo, dirpath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
```

**Comment by AlbinoGeek** [comment]
# Why do I need to build from source?

Your packages on Fedora / Python3 pip are **severely** outdated, giving only 0.1.2 where the application requires 0.2.1 to be installed.

**Comment by maxpumperla** [comment]
@AlbinoGeek you're telling me `pip install hyperopt==0.2.1` does not work on Fedora? that's more than a little surprising. https://pypi.org/project/hyperopt/ as you can see 0.2.2 is on pypi, not sure what else you would need.

OK, `distribute_setup.py` I think nobody has looked at for a while. Do you really need MongoDB support right now? If not, you could at least continue your build for now by dropping `MongoTrials`.

**Comment by AlbinoGeek** [comment]
I can install hyperopt `0.2.1` using the command you specified.

However, my original issue stands (build instructions not working for either version.)

---

Separately, (and this might not be your project's issue, but if it is, needs a new issue opened):

```
$ pip3 install mycroft-precise rasa
... snip ...
bbopt 1.1.8 has requirement hyperopt>=0.2.1, but you'll have hyperopt 0.1.2 which is incompatible.  
... snip ...
rasa 1.4.3 has requirement networkx~=2.3.0, but you'll have networkx 2.2 which is incompatible.              
mycroft-precise 0.3.0 has requirement hyperopt==0.1.2, but you'll have hyperopt 0.2.2 which is incompatible.
mycroft-precise 0.3.0 has requirement networkx==1.11, but you'll have networkx 2.2 which is incompatible.
mycroft-precise 0.3.0 has requirement tensorflow<1.14,>=1.13, but you'll have tensorflow 1.14.0 which is incompatible.
... snip ...
```

I assume this is a problem in their deps file.
