### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by GuillaumeDesforges** [hyperopt/hyperopt#580]
I am packaging hyperopt for nixpkgs.

When building with test, I get this error:

```
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 156, in <module>
    zip_safe=False
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 259, in run_tests
    exit=False,
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/i1xm831hj7wncmh6xb532flr7i522l04-python3.7-setuptools-41.6.0/lib/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/drr8qcgiccfc5by09r5zc30flgwh1mbx-python3-3.7.5/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: fmin() missing 4 required positional arguments: 'fn', 'space', 'algo', and 'max_evals'
```

**Comment by maxpumperla** [comment]
@GuillaumeDesforges how exactly are you building/testing this? the error seems to stem from the `unittest` framework during test discovery. I need some more context. it seems to search for a test for "fmin" and then fails to initialize it?

we currently use `nose` internally.

**Comment by GuillaumeDesforges** [comment]
Hello @maxpumperla , I am creating a package using Nix, a purely functional package manager.

My PR for the packaging can be found here : https://github.com/NixOS/nixpkgs/pull/74783

Thank you for your reply, I didn't know you were using `nose`. [This has fixed the problem](https://github.com/NixOS/nixpkgs/issues/26588#issuecomment-308791290).

**Comment by maxpumperla** [comment]
we use nose on travis, see here:
https://github.com/hyperopt/hyperopt/blob/master/run_tests.sh#L96
