### ISSUE TITLE
ERROR:hyperopt.fmin:job exception: 'dict' object is not callable

### ISSUE THREAD

**Issue by LysSanzMoreta** [hyperopt/hyperopt#722]
Hi!

First thanks for your attention. Second , I believe I am using the objective function correctly by returning adictionary like this (simplified code) : 

```
def sampling(**args): 
            #lots of model stuff
            return {'loss': -score, 'status': STATUS_OK}

def bayesian_optimization(**args):
           objective_funtion = sampling(**args) #I have a lot of arguments here, I hope that is feasible
           trials = Trials()
           best_param = fmin(objective_function, #The error appears here
                      param_space,
                      algo=tpe.suggest,
                      max_evals=num_eval,
                      trials=trials,
                      rstate=seed)
          score = [x['result']['score'] for x in trials.trials]
          best_param_values = [x for x in best_param.values()]
         
          return trials
```

However, it only runs one trial and in the second one I receive this error showing that it does not accept the dictionary, however I was convinced it needs a dictionary: 

```
ERROR:hyperopt.fmin:job exception: 'dict' object is not callable
Traceback (most recent call last):
  File "...", line 1097, in <module>
    aa_prob)
  File "...", line 952, in bayesian_hyperparameter_optimization
    rstate=seed)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/base.py", line 686, in fmin
    show_progressbar=show_progressbar,
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 509, in fmin
    rval.exhaust()
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 286, in run
    self.serial_evaluate()
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py", line 165, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/hyperopt/base.py", line 894, in evaluate
    rval = self.fn(pyll_rval)
TypeError: 'dict' object is not callable
```

I am I doing somehing in the wrong order? Thank you very much for your help :)

**Comment by LysSanzMoreta** [comment]
Ok, I solved it by rearranging a couple of things:

def objective_function(param_space):
             model() # as a function inside the objective function!!
             #compute loss
             return {"loss":loss_value}
