### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by joachimwolff** [hyperopt/hyperopt#768]
Hi,

I used `algo=atpe.suggest` for fmin and got this error after 9 runs:

```
INFO:hyperopt.tpe:TPE using 9/9 trials with best loss 0.479384
ERROR:hyperopt.fmin:job exception: list index out of range
 26%|██████████████████████                                                               | 13/50 [17:57<51:06, 82.87s/trial, best loss: 0.4793837876540882]
Traceback (most recent call last):
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/bin/scHicClusterMinHashHyperopt", line 7, in <module>
    main()
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/schicexplorer/scHicClusterMinHashHyperopt.py", line 187, in main
    best = fmin(objective, space, algo=atpe.suggest, max_evals=args.runs, trials=trials)
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/fmin.py", line 522, in fmin
    trials_save_file=trials_save_file,
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/base.py", line 699, in fmin
    trials_save_file=trials_save_file,
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/fmin.py", line 553, in fmin
    rval.exhaust()
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/fmin.py", line 292, in run
    self.serial_evaluate()
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/base.py", line 905, in evaluate
    print_node_on_error=self.rec_eval_print_node_on_error,
  File "/home/wolffj/miniconda3/envs/minhash_scanpy_py36_new/lib/python3.6/site-packages/hyperopt/pyll/base.py", line 874, in rec_eval
    rval_var = node.pos_args[int(switch_i) + 1]
IndexError: list index out of range

``` 

I am not sure if this is caused by me or if it is an internal hyperopt error.

Best,

Joachim

**Comment by SSS135** [comment]
Hi,
Same problem here. Code to reproduce:
```
from hyperopt import hp, atpe
from hyperopt.fmin import fmin
import numpy as np
import math
from hyperopt.pyll import scope as ho_scope

space = {
    'use_mean': hp.choice('use_mean', [False, True]),
    'use_std': hp.choice('use_std', [False, True]),
    'use_count': hp.choice('use_count', [False, True]),
}

def score(params):
    return np.random.rand()

best = fmin(fn=score, space=space, algo=atpe.suggest, max_evals=1000)
```

**Comment by benedikth** [comment]
Hi,
same here using:
`   
from hyperopt import hp, tpe, fmin, STATUS_OK, STATUS_FAIL, Trials

space = {
        'batch_size': hp.choice('batch_size', [2, 4, 8, 16]),
        'lr': hp.choice('lr', [10 ** (-i) for i in range(1, 10, 1)]),
        'patience': hp.choice('patience', [i for i in range(2, 21, 1)]),
        'weight_decay': hp.choice(
            'weight_decay', [10 ** (-i) for i in range(1, 5, 1)]
        ),
        'amsgrad': hp.choice('amsgrad', [True, False])
    }
best = fmin(
                fn=objective,
                space=space,
                algo=tpe.suggest,
                trials=trials,
                max_evals=iteration_counter + 1
           )
`
