### ISSUE TITLE
AssertionError: group argument must be None for now - when doing fit

### ISSUE THREAD

**Issue by ericvoots** [hyperopt/hyperopt#792]
Here is my code

```

            from hypopt import GridSearch
            parameters = {'n_neighbors':[1,2]}
            # Grid-search all parameter combinations using a validation set.
            opt = GridSearch(model = KNeighborsClassifier(metric=DTW), param_grid = parameters)
            opt.fit(train_x, train_y, cv_x, cv_y, scoring='f1')
            print('Test Score for Optimized Parameters:', opt.score(cv_x, cv_y))


            #evaluate
            y_pred = opt.predict(cv_x)
            print(classification_report(cv_y, y_pred))
            print(opt._best_params_)

```

Here is the traceback

Traceback (most recent call last):
  File "WeeklyModelData.py", line 411, in <module>
    model_runs(config_classification=config_classification,
  File "WeeklyModelData.py", line 331, in model_runs
    opt.fit(train_x, train_y, cv_x, cv_y)
  File "/usr/local/lib/python3.8/dist-packages/hypopt/model_selection.py", line 360, in fit
    results = _parallel_param_opt(params, self.num_threads)
  File "/usr/local/lib/python3.8/dist-packages/hypopt/model_selection.py", line 185, in _parallel_param_opt
    with multiprocessing_context(
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 319, in _repopulate_pool_static
    w = Process(ctx, target=worker,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 82, in __init__
    assert group is None, 'group argument must be None for now'

**Comment by lbiester** [comment]
I am seeing the same thing!

**Comment by jyuelai** [comment]
Same problem on opt.fit(x_train, y_train, x_val, y_val).

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-48-b16db3e9c023> in <module>
      5 
      6 opt = GridSearch(model = RandomForestClassifier(), param_grid = param_grid)
----> 7 opt.fit(x_train, y_train, x_val, y_val)
      8 print('Test Score for Optimized Parameters:', opt.score(x_val, y_val))

D:\Anaconda3\envs\py38\lib\site-packages\hypopt\model_selection.py in fit(self, X_train, y_train, X_val, y_val, scoring, scoring_params, verbose)
    358             )
    359             if self.parallelize:
--> 360                 results = _parallel_param_opt(params, self.num_threads)
    361             else:
    362                 results = [_run_thread_job(job) for job in params]

D:\Anaconda3\envs\py38\lib\site-packages\hypopt\model_selection.py in _parallel_param_opt(jobs, num_threads)
    183         num_threads = multiprocessing.cpu_count()
    184     K = len(jobs)
--> 185     with multiprocessing_context(
    186         num_threads,
    187 #         initializer=_make_shared_immutables_global,

D:\Anaconda3\envs\py38\lib\multiprocessing\pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    210         self._processes = processes
    211         try:
--> 212             self._repopulate_pool()
    213         except Exception:
    214             for p in self._pool:

D:\Anaconda3\envs\py38\lib\multiprocessing\pool.py in _repopulate_pool(self)
    301 
    302     def _repopulate_pool(self):
--> 303         return self._repopulate_pool_static(self._ctx, self.Process,
    304                                             self._processes,
    305                                             self._pool, self._inqueue,

D:\Anaconda3\envs\py38\lib\multiprocessing\pool.py in _repopulate_pool_static(ctx, Process, processes, pool, inqueue, outqueue, initializer, initargs, maxtasksperchild, wrap_exception)
    317         """
    318         for i in range(processes - len(pool)):
--> 319             w = Process(ctx, target=worker,
    320                         args=(inqueue, outqueue,
    321                               initializer,

D:\Anaconda3\envs\py38\lib\multiprocessing\process.py in __init__(self, group, target, name, args, kwargs, daemon)
     80     def __init__(self, group=None, target=None, name=None, args=(), kwargs={},
     81                  *, daemon=None):
---> 82         assert group is None, 'group argument must be None for now'
     83         count = next(_process_counter)
     84         self._identity = _current_process._identity + (count,)

AssertionError: group argument must be None for now

**Comment by Ibrasalma** [comment]
Hello did anyone get this fixed?

**Comment by ferdifdi** [comment]
Hello did anyone can fix that?

**Comment by ostrowii** [comment]
Fix?

**Comment by joysarkar11** [comment]
seeing the same, was anyone able to fix it?
