### ISSUE TITLE
hyperopt with xgboost show Typeerror on hyperparameters.

### ISSUE THREAD

**Issue by qianyu-berkeley** [hyperopt/hyperopt#806]
I got a data type error when using hyperopt with xgboost package. The error message points to a parameter that is not in the defined space.

I tested with xgboost version 1.1.1 and 1.3.1. The xgboost module works on its own.

```
def train(params):
  
  # Define XGBoost model
  xgb = XGBClassifier(
    learning_rate=params["learning_rate"],
    n_estimators=params["n_estimators"],
    colsample_bytree=params["colsample_bytree"],
    max_depth=params["max_depth"],
    reg_alpha=params["reg_alpha"]
  )   
  xgb.fit(X_train, y_train)
  y_pred = xgb.predict(X_val)
  y_score = xgb.predict_proba(X_val)
  log_loss= metrics.log_loss(y_val, y_score)
  return {"loss": log_loss, 
          "status": STATUS_OK}

space = {
  "learning_rate": hp.loguniform("learning_rate", -4, 0),
  "n_estimators": hp.quniform("n_estimator", 100, 1000, 1500),
  "colsample_bytree": hp.uniform("colsample_bytree", 0.5, 1),
  "max_depth": hp.uniform("max_depth", 3, 10),
  "reg_alpha": hp.loguniform("reg_alpha", -3, 0)
}

spark_trials = SparkTrials(parallelism=8)

with mlflow.start_run(run_name="sku_recom_experiment"):
  best_model = fmin(fn=train, 
                    space=space, 
                    algo=tpe.suggest, 
                    max_evals=20, 
                    trials=spark_trials)
```

errors message:
```
0%|          | 0/20 [00:00<?, ?trial/s, best loss=?]trial task 0 failed, exception is 'float' object cannot be interpreted as an integer.
 Traceback (most recent call last):
  File "/databricks/python/lib/python3.7/site-packages/hyperopt/spark.py", line 482, in run_task_on_executor
    params, ctrl=None, attach_attachments=False
  File "/databricks/python/lib/python3.7/site-packages/hyperopt/base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "<command-136028>", line 25, in train
  File "/databricks/python/lib/python3.7/site-packages/xgboost/sklearn.py", line 824, in fit
    early_stopping_rounds=None, verbose=True, xgb_model=None,
  File "/databricks/python/lib/python3.7/site-packages/xgboost/training.py", line 214, in train
    early_stopping_rounds=early_stopping_rounds)
  File "/databricks/python/lib/python3.7/site-packages/xgboost/training.py", line 95, in _train_internal
    for i in range(start_iteration, num_boost_round):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by fridrichmrtn** [comment]
@solegalli is on point with the error, but the problem is better solved directly in the space definition - just use `hp.randint` with lower and upper boundaries as an argument for the `n_estimators` and `max_depth`. The search will be more efficient.
