### ISSUE TITLE
New release 0.2.6 miss component 'py4j'

### ISSUE THREAD

**Issue by chensuyue** [hyperopt/hyperopt#826]
>>> import hyperopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tensorflow/miniconda3/lib/python3.9/site-packages/hyperopt/__init__.py", line 39, in <module>
    from .spark import SparkTrials
  File "/home/tensorflow/miniconda3/lib/python3.9/site-packages/hyperopt/spark.py", line 11, in <module>
    from py4j.clientserver import ClientServer
ModuleNotFoundError: No module named 'py4j'

**Comment by chensuyue** [comment]
Hi @maxpumperla, would you have a patch release for this issue?

**Comment by maxpumperla** [comment]
@chensuyue good catch, I'm on it.
